version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://ajiro.ir/api
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ./startup.sh
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./backend/.env.production
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - api
    restart: always

  postgres:
    image: postgres:15-alpine
    ports:
      - "5437:5437"
    command: -p 5437
    environment:
      - POSTGRES_PASSWORD=1374Ali!1995
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ajiro
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ajiro -p 5437"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: 