version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
    # No volume mount for source code in production
    
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: node src/index.js
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      # In production, these would be set via environment variables
      # or docker secrets, not hardcoded here
    # No volume mount for source code in production

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - api
    restart: always
    
  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/backups:/backups
      
  redis:
    restart: always
    volumes:
      - redis_data:/data 